/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    listings: Listing;
    districts: District;
    'price-quarters': PriceQuarter;
    advisors: Advisor;
    developers: Developer;
    articles: Article;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    'price-quarters': PriceQuartersSelect<false> | PriceQuartersSelect<true>;
    advisors: AdvisorsSelect<false> | AdvisorsSelect<true>;
    developers: DevelopersSelect<false> | DevelopersSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Only a Super Admin can manage other staff Users and permissions (FR-313).
   */
  roles: ('editor' | 'super-admin')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Recommended for accessibility, not hard-required — see docs/FSD.md FR-312.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: number;
  title: string;
  /**
   * Auto-generated from the title (FR-409) — not editable directly.
   */
  slug?: string | null;
  category: 'residential-land' | 'developed-residence' | 'commercial-plot';
  district: number | District;
  size: number;
  pricePerSqm: number;
  /**
   * Computed as size × ₦/sqm on save — not entered directly.
   */
  price?: number | null;
  /**
   * A listing is only ever publicly visible when Published (FR-106, FR-110).
   */
  status: 'draft' | 'published';
  plan?: boolean | null;
  docs: {
    cofo: 'verified' | 'progress' | 'pending';
    survey: 'verified' | 'progress' | 'pending';
    registry: 'verified' | 'progress' | 'pending';
    deed: 'verified' | 'progress' | 'pending';
  };
  useCase?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  advisor?: (number | null) | Advisor;
  developer?: (number | null) | Developer;
  photos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: number;
  name: string;
  /**
   * Drives the two-series prime-vs-suburban chart on Home and the index figures on the Market Hub (FR-104, FR-402).
   */
  tier: 'prime' | 'suburban';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisors".
 */
export interface Advisor {
  id: number;
  name: string;
  /**
   * e.g. "Senior Advisor, Prime Districts"
   */
  patch?: string | null;
  phone: string;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers".
 */
export interface Developer {
  id: number;
  name: string;
  /**
   * e.g. "14 estates delivered since 2011"
   */
  delivered?: string | null;
  /**
   * e.g. "96% handovers on schedule"
   */
  onSchedule?: string | null;
  /**
   * Should only be checked once the FR-103 developer-standing check has actually been completed — see docs/product-owner/open-questions.md OQ-011.
   */
  verifiedPartner?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Updated every quarter by the named data owner (see docs/project-overview.md Section 9). PBI-305 will add a bulk-entry grid view so all six districts can be updated in one screen instead of one record at a time.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-quarters".
 */
export interface PriceQuarter {
  id: number;
  district: number | District;
  /**
   * Fixed format, e.g. "Q2 2026".
   */
  quarter: string;
  land: number;
  residential: number;
  /**
   * Quarter-over-quarter percentage change versus this district's prior quarter entry.
   */
  qoq?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  slug: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  type: 'general' | 'inspection' | 'callback';
  name: string;
  phone: string;
  email?: string | null;
  basedIn?: string | null;
  listing?: (number | null) | Listing;
  /**
   * Must be today or later — validated in the Server Action, not just here.
   */
  preferredDate?: string | null;
  mode?: ('in-person' | 'virtual' | 'representative') | null;
  timezone?: string | null;
  /**
   * Must be true to submit — enforced server-side (FR-120).
   */
  consent: boolean;
  status: 'new' | 'in-review' | 'advisor-assigned' | 'closed';
  advisor?: (number | null) | Advisor;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'listings';
        value: number | Listing;
      } | null)
    | ({
        relationTo: 'districts';
        value: number | District;
      } | null)
    | ({
        relationTo: 'price-quarters';
        value: number | PriceQuarter;
      } | null)
    | ({
        relationTo: 'advisors';
        value: number | Advisor;
      } | null)
    | ({
        relationTo: 'developers';
        value: number | Developer;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  district?: T;
  size?: T;
  pricePerSqm?: T;
  price?: T;
  status?: T;
  plan?: T;
  docs?:
    | T
    | {
        cofo?: T;
        survey?: T;
        registry?: T;
        deed?: T;
      };
  useCase?: T;
  advisor?: T;
  developer?: T;
  photos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  tier?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-quarters_select".
 */
export interface PriceQuartersSelect<T extends boolean = true> {
  district?: T;
  quarter?: T;
  land?: T;
  residential?: T;
  qoq?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisors_select".
 */
export interface AdvisorsSelect<T extends boolean = true> {
  name?: T;
  patch?: T;
  phone?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "developers_select".
 */
export interface DevelopersSelect<T extends boolean = true> {
  name?: T;
  delivered?: T;
  onSchedule?: T;
  verifiedPartner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  phone?: T;
  email?: T;
  basedIn?: T;
  listing?: T;
  preferredDate?: T;
  mode?: T;
  timezone?: T;
  consent?: T;
  status?: T;
  advisor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}